import { json } from '@sveltejs/kit';
import { join } from 'path';
import {
	getLatestSnapshot,
	getGridData,
	getGridDataForRange,
	indicatorColumn
} from '$lib/server/weather.js';
import { cachedFile } from '$lib/server/fileCache.js';
import type { RequestHandler } from './$types';

// Data is regenerated by the fetch cron every ~3 h. Keep the browser cache
// short so a returning visitor sees fresh figures within minutes of an update,
// while stale-while-revalidate keeps responses instant across a full cycle.
const CACHE_HEADER = 'public, max-age=300, stale-while-revalidate=10800';

const PRESET_FILES: Record<string, string> = {
	today:  join(process.cwd(), 'data', 'grid-latest.geojson'),
	last7d: join(process.cwd(), 'data', 'grid-last7d.geojson'),
	next3d: join(process.cwd(), 'data', 'grid-next3d.geojson'),
};

// The fetch pipeline writes both `<preset>.geojson` and a pre-compressed
// `<preset>.geojson.gz`. We serve the .gz directly with Content-Encoding: gzip
// so there is NO on-the-fly compression — the first visitor after a refresh
// gets the ~3 MB payload at full speed instead of waiting ~24 s for the proxy
// to gzip 45 MB. Both are served from an in-memory cache that refreshes in the
// background (never blocking a request on disk I/O — see fileCache.ts), so the
// first load right after a fetch is just as fast as every subsequent one.

// Eagerly prime the small, hot .gz payloads at boot. The large raw fallbacks
// (.geojson, only hit when the client can't accept gzip) are created lazily.
for (const filePath of Object.values(PRESET_FILES)) cachedFile(filePath + '.gz');

function loadRaw(preset: string): string | null {
	const filePath = PRESET_FILES[preset];
	if (!filePath) return null;
	return cachedFile(filePath).getText();
}

function loadGz(preset: string): Uint8Array | null {
	const filePath = PRESET_FILES[preset];
	if (!filePath) return null;
	return cachedFile(filePath + '.gz').getBuffer();
}

function todayRange(): { from: string; to: string } {
	const now = new Date();
	const from = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), 0, 0, 0));
	const to = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), 23, 59, 59));
	return { from: from.toISOString(), to: to.toISOString() };
}

export const GET: RequestHandler = async ({ url, request }) => {
	const indicator = indicatorColumn(url.searchParams.get('indicator'));
	const preset = url.searchParams.get('preset');
	const period = url.searchParams.get('period') || 'now';

	// Fast path: serve the pre-generated GeoJSON FeatureCollection for known
	// presets. The response body is the FeatureCollection itself (raw indicator
	// values; isAffected/colour are computed client-side per the active view).
	const fastPathPreset = preset ?? (url.searchParams.get('from') ? null : 'today');
	if (fastPathPreset && fastPathPreset in PRESET_FILES) {
		const acceptsGzip = (request.headers.get('accept-encoding') || '').includes('gzip');
		if (acceptsGzip) {
			const gz = loadGz(fastPathPreset);
			if (gz) {
				// Cast: a Uint8Array body is valid in the Node/adapter-node runtime,
				// but the DOM `BodyInit` type (TS lib) doesn't model it.
				return new Response(gz as unknown as BodyInit, {
					headers: {
						'Content-Type': 'application/json',
						'Content-Encoding': 'gzip',
						'Vary': 'Accept-Encoding',
						'Cache-Control': CACHE_HEADER,
					},
				});
			}
		}
		const raw = loadRaw(fastPathPreset);
		if (raw) {
			return new Response(raw, {
				headers: {
					'Content-Type': 'application/json',
					'Vary': 'Accept-Encoding',
					'Cache-Control': CACHE_HEADER,
				},
			});
		}
		// File not yet generated — fall through to DB path below
	}

	// Range path (last7d, next3d, custom) — query the database
	let from = url.searchParams.get('from');
	let to = url.searchParams.get('to');

	if (!from || !to) {
		if (preset === 'today') {
			({ from, to } = todayRange());
		} else if (preset === 'last7d') {
			from = new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString();
			to = new Date().toISOString();
		} else if (preset === 'next3d') {
			from = new Date().toISOString();
			to = new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString();
		} else if (period === '24h') {
			from = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
			to = new Date().toISOString();
		} else if (period === '7d') {
			from = new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString();
			to = new Date().toISOString();
		}
	}

	let grid: any[];

	if (!from || !to) {
		const snapshot = getLatestSnapshot();
		if (!snapshot) {
			return json({ error: 'No data available yet.' }, { status: 404 });
		}
		grid = getGridData(snapshot.id);
	} else {
		const threshold = Number(url.searchParams.get('threshold') || process.env.HEAT_THRESHOLD || 30);
		grid = getGridDataForRange(from, to, indicator, threshold);
	}

	if (grid.length === 0) {
		return json({ error: 'No data available for this time range.' }, { status: 404 });
	}

	const geojson = {
		type: 'FeatureCollection' as const,
		features: grid.map((cell: any) => ({
			type: 'Feature' as const,
			geometry: { type: 'Point' as const, coordinates: [cell.lon, cell.lat] },
			properties: {
				country: cell.country,
				population: cell.population,
				lat: Math.round(cell.lat * 1000) / 1000,
				lon: Math.round(cell.lon * 1000) / 1000,
				temperature: cell.temperature,
				apparentTemperature: cell.apparentTemperature,
				...(cell.minTemperature      !== undefined && { minTemperature:         cell.minTemperature }),
				...(cell.minApparentTemperature !== undefined && { minApparentTemperature: cell.minApparentTemperature }),
			}
		}))
	};

	// Return the FeatureCollection directly (matches the fast-path shape).
	return json(geojson, { headers: { 'Cache-Control': CACHE_HEADER } });
};
