import { json } from '@sveltejs/kit';
import { join } from 'path';
import {
	getLatestSnapshot,
	getCountryAggregates,
	getPeriodSummaryForRange,
	getCountryAggregatesForRange,
	getAvailableRange,
	indicatorColumn
} from '$lib/server/weather.js';
import { cachedFile } from '$lib/server/fileCache.js';
import type { RequestHandler } from './$types';

// Data is regenerated by the fetch cron every ~3 h. Keep the browser cache
// short so a returning visitor sees fresh figures within minutes of an update,
// while stale-while-revalidate keeps responses instant across a full cycle.
// (A long max-age here previously meant updated headlines could be hidden for
// up to 3 h after the climatology/data refreshed.)
const CACHE_HEADER = 'public, max-age=300, stale-while-revalidate=10800';
const DEFAULT_THRESHOLD = Number(process.env.HEAT_THRESHOLD) || 30;

// Pre-generated static JSON files, written by scripts/fetch-dwd.py after every
// data refresh so the first visitor never waits for a DB query.
const CURRENT_PRESET_FILES: Record<string, string> = {
	today:  join(process.cwd(), 'data', 'current-today.json'),
	last7d: join(process.cwd(), 'data', 'current-last7d.json'),
	next3d: join(process.cwd(), 'data', 'current-next3d.json'),
};

// Served from an in-memory cache that refreshes in the background (never blocks
// a request on disk I/O — see fileCache.ts), so the first load right after a
// fetch run is as fast as every subsequent one. Prime the small files at boot.
for (const filePath of Object.values(CURRENT_PRESET_FILES)) cachedFile(filePath);

function loadPreGeneratedCurrent(preset: string): string | null {
	const filePath = CURRENT_PRESET_FILES[preset];
	if (!filePath) return null;
	return cachedFile(filePath).getText();
}

/**
 * Extract the climatology-derived headline fields from a pre-generated current
 * file. These are indicator-INDEPENDENT — meanAnomalyC and popAboveAvg are
 * computed from raw 2m temperature against the E-OBS daily-mean climatology and
 * are the same regardless of whether the user has selected "temperature"
 * or "apparent_temperature" as the active indicator. We extract them
 * here so the DB-path response (used for non-default indicator/threshold
 * combinations) can still surface them to the headline UI.
 */
function getClimatologyFromPregen(preset: string): {
	snapshot: { meanAnomalyC: number | null; popAboveAvg: number; referencePeriod: string } | null;
	countriesByCode: Map<string, { avgAnomalyC: number | null; popAboveAvg: number }>;
} {
	const empty = { snapshot: null, countriesByCode: new Map() };
	const raw = loadPreGeneratedCurrent(preset);
	if (!raw) return empty;
	try {
		const data = JSON.parse(raw);
		const snap = data.snapshot ?? {};
		const out: ReturnType<typeof getClimatologyFromPregen> = {
			snapshot: snap.referencePeriod
				? {
					meanAnomalyC: snap.meanAnomalyC ?? null,
					popAboveAvg: snap.popAboveAvg ?? 0,
					referencePeriod: snap.referencePeriod,
				}
				: null,
			countriesByCode: new Map(),
		};
		for (const c of data.countries ?? []) {
			if (c.country) {
				out.countriesByCode.set(c.country, {
					avgAnomalyC: c.avgAnomalyC ?? null,
					popAboveAvg: c.popAboveAvg ?? 0,
				});
			}
		}
		return out;
	} catch {
		return empty;
	}
}

/** Convert legacy period param to ISO from/to range */
function periodToRange(period: string): { from: string; to: string } | null {
	const hours: Record<string, number> = { '24h': 24, '7d': 168 };
	if (period === 'now') return null;
	const h = hours[period];
	if (!h) return null;
	return {
		from: new Date(Date.now() - h * 3600 * 1000).toISOString(),
		to: new Date().toISOString()
	};
}

/** Compute today's UTC range (00:00 – 23:59:59) */
function todayRange(): { from: string; to: string } {
	const now = new Date();
	const from = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), 0, 0, 0));
	const to = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), 23, 59, 59));
	return { from: from.toISOString(), to: to.toISOString() };
}

export const GET: RequestHandler = async ({ url }) => {
	const indicator = indicatorColumn(url.searchParams.get('indicator'));
	const threshold = Number(url.searchParams.get('threshold') || DEFAULT_THRESHOLD);

	// Determine time range from params
	// Priority: explicit from/to > preset > legacy period
	let from = url.searchParams.get('from');
	let to = url.searchParams.get('to');
	const preset = url.searchParams.get('preset');
	const period = url.searchParams.get('period') || 'now';

	if (!from || !to) {
		if (preset === 'today') {
			({ from, to } = todayRange());
		} else if (preset === 'last7d') {
			from = new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString();
			to = new Date().toISOString();
		} else if (preset === 'next3d') {
			from = new Date().toISOString();
			to = new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString();
		} else {
			const legacyRange = periodToRange(period);
			if (legacyRange) {
				({ from, to } = legacyRange);
			}
		}
	}

	// Fast path: serve pre-generated JSON for known presets.
	// Files are written atomically by scripts/fetch-dwd.py after every run,
	// so the first visitor after a data refresh is served from disk instantly.
	// Only valid for default indicator + threshold — custom requests must hit the DB.
	const requestedIndicator = url.searchParams.get('indicator');
	const requestedThreshold = url.searchParams.get('threshold');
	const isDefaultRequest =
		(!requestedIndicator || requestedIndicator === 'temperature') &&
		(!requestedThreshold || Number(requestedThreshold) === DEFAULT_THRESHOLD);
	const fastPathPreset = isDefaultRequest ? (preset ?? (from ? null : 'today')) : null;
	if (fastPathPreset && fastPathPreset in CURRENT_PRESET_FILES) {
		const raw = loadPreGeneratedCurrent(fastPathPreset);
		if (raw) {
			return new Response(raw, {
				headers: {
					'Content-Type': 'application/json',
					'Cache-Control': CACHE_HEADER,
				},
			});
		}
		// File not yet generated — fall through to DB path below
	}

	const availableRange = getAvailableRange();

	// Single-snapshot mode (period=now or no range specified)
	if (!from || !to) {
		const snapshot = getLatestSnapshot();
		if (!snapshot) {
			return json(
				{ error: 'No data available yet. Run: python scripts/fetch-dwd.py', hint: 'POST /api/fetch to trigger a legacy fetch' },
				{ status: 404 }
			);
		}
		const countries = getCountryAggregates(snapshot.id);
		return json({
			snapshot: {
				id: snapshot.id,
				timestamp: snapshot.timestamp,
				totalAffected: snapshot.totalAffected,
				totalPopulation: snapshot.totalPopulation,
				thresholdCelsius: snapshot.thresholdCelsius ?? threshold,
				isForecast: !!snapshot.isForecast,
				hasForecast: false,
				modelRunTime: snapshot.modelRunTime ?? null
			},
			countries,
			indicator,
			period: 'now',
			availableRange
		}, { headers: { 'Cache-Control': CACHE_HEADER } });
	}

	// Range mode
	const summary = getPeriodSummaryForRange(from, to, indicator, threshold);
	if (!summary) {
		const hasAny = !!getAvailableRange();
		return json({
			error: hasAny
				? 'No data available for this time range.'
				: 'No data available yet. Run: python scripts/fetch-dwd.py'
		}, { status: 404 });
	}

	const latest = getLatestSnapshot();
	const countries = getCountryAggregatesForRange(from, to, indicator, threshold);

	// Overlay climatology headline fields from the pre-generated preset file.
	// `clim_preset` lets callers specify a different preset for climatology than
	// for the date range (e.g. tomorrow's range query wants next3d climatology).
	const climPresetParam = url.searchParams.get('clim_preset');
	const climPreset =
		(climPresetParam && climPresetParam in CURRENT_PRESET_FILES)
			? climPresetParam
			: (preset && preset in CURRENT_PRESET_FILES ? preset : null);
	const clim = climPreset ? getClimatologyFromPregen(climPreset) : null;

	return json({
		snapshot: {
			timestamp: summary.newestTimestamp,
			totalAffected: summary.totalAffected,
			totalPopulation: summary.totalPopulation,
			thresholdCelsius: latest?.thresholdCelsius ?? threshold,
			snapshotCount: summary.snapshotCount,
			oldestTimestamp: summary.oldestTimestamp,
			hasForecast: summary.hasForecast,
			modelRunTime: summary.latestModelRunTime ?? null,
			// Prefer the pre-generated clim overlay; fall back to the DB-computed
			// area-mean anomaly (available whenever anomaly_c is in grid_data).
			meanAnomalyC: clim?.snapshot?.meanAnomalyC ?? summary.meanAnomalyC ?? null,
			popAboveAvg: clim?.snapshot?.popAboveAvg ?? 0,
			referencePeriod: clim?.snapshot?.referencePeriod ?? (summary.meanAnomalyC != null ? '1961–1990' : undefined),
		},
		countries: countries.map((c: any) => {
			const extra = clim?.countriesByCode.get(c.country);
			return extra ? { ...c, avgAnomalyC: extra.avgAnomalyC, popAboveAvg: extra.popAboveAvg } : c;
		}),
		indicator,
		period: preset || period,
		from,
		to,
		availableRange
	}, { headers: { 'Cache-Control': CACHE_HEADER } });
};
